@baseurl = https://localhost:7031

### POST request to initializeDemandLetter endpoint
POST {{baseurl}}/ArtifactGeneration/initializeDemandLetter
Content-Type: application/json

{
  "userMessage": "I hired a contractor in Montreal to renovate my kitchen, with a signed contract stating work would be completed by September 30, 2024, for $25,000. I paid a $10,000 deposit, but as of October 15, the contractor abandoned the project with only 30% completed and has not responded to my attempts to contact them. I am demanding the return of my $10,000 deposit and $5,000 in additional compensation to cover increased costs caused by their failure to fulfill the contract."
}

###
POST {{baseurl}}/ArtifactGeneration/GetNextQuestion
Content-Type: application/json

{
  "ArtifactId": 9
}

###
POST {{baseurl}}/ArtifactGeneration/SubmitMoreInformation
Content-Type: application/json

{
  "ArtifactId": 8,
  "UserResponse": "My name is John Adams. The first name of the person I was in contact with is Bernard.",
  "UserQuestion": "Could you please provide the full name of the plaintiff, including their first and last names, as well as the date on which the events occurred, and the first name of the accused?"
}